Search.appendIndex(
    [
                {
            "fqsen": "\\Config\\CustomRules",
            "name": "CustomRules",
            "summary": "CustomRules\u0020is\u0020a\u0020Class\u0020that\u0020provides\u0020custom\u0020form\u0020validation\u0020rules\u0020for\u0020this\u0020app.",
            "url": "classes/Config-CustomRules.html"
        },                {
            "fqsen": "\\Config\\CustomRules\u003A\u003Averify_recaptcha\u0028\u0029",
            "name": "verify_recaptcha",
            "summary": "Verify\u0020Recaptcha\u0020is\u0020a\u0020basic\u0020function\u0020for\u0020sending\u0020and\u0020verifying\u0020Recaptcha\u0020V3\u0020token\u0020to\u0020Google.",
            "url": "classes/Config-CustomRules.html#method_verify_recaptcha"
        },                {
            "fqsen": "\\Config\\CustomRules\u003A\u003Aphone_number\u0028\u0029",
            "name": "phone_number",
            "summary": "Simple\u0020validation\u0020for\u0020correct\u0020phone\u0020number\u0020format.\u0020\u0028Only\u0020accept\u0020Indonesian\u0020Country\u0020Code\u0029.",
            "url": "classes/Config-CustomRules.html#method_phone_number"
        },                {
            "fqsen": "\\Config\\Services",
            "name": "Services",
            "summary": "Services\u0020Configuration\u0020file.",
            "url": "classes/Config-Services.html"
        },                {
            "fqsen": "\\Config\\Services\u003A\u003Aredirectresponse\u0028\u0029",
            "name": "redirectresponse",
            "summary": "Override\u0020redirect\u0020response\u0020base\u0020service\u0020with\u0020new\u0020one",
            "url": "classes/Config-Services.html#method_redirectresponse"
        },                {
            "fqsen": "\\Config\\Validation",
            "name": "Validation",
            "summary": "Validation\u0020Rule\u0020Groups",
            "url": "classes/Config-Validation.html"
        },                {
            "fqsen": "\\Config\\Validation\u003A\u003A\u0024ruleSets",
            "name": "ruleSets",
            "summary": "Stores\u0020the\u0020classes\u0020that\u0020contain\u0020the\nrules\u0020that\u0020are\u0020available.",
            "url": "classes/Config-Validation.html#property_ruleSets"
        },                {
            "fqsen": "\\Config\\Validation\u003A\u003A\u0024templates",
            "name": "templates",
            "summary": "Specifies\u0020the\u0020views\u0020that\u0020are\u0020used\u0020to\u0020display\u0020the\nerrors.",
            "url": "classes/Config-Validation.html#property_templates"
        },                {
            "fqsen": "\\Config\\Validation\u003A\u003A\u0024gRecaptcha",
            "name": "gRecaptcha",
            "summary": "Recaptcha\u0020rule.",
            "url": "classes/Config-Validation.html#property_gRecaptcha"
        },                {
            "fqsen": "\\Config\\Validation\u003A\u003A\u0024spreadsheet",
            "name": "spreadsheet",
            "summary": "Spreadsheet\u0020upload\u0020rule.",
            "url": "classes/Config-Validation.html#property_spreadsheet"
        },                {
            "fqsen": "\\App\\Controllers\\Auth",
            "name": "Auth",
            "summary": "Authentication\u0020Controller.",
            "url": "classes/App-Controllers-Auth.html"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020UsersModel.",
            "url": "classes/App-Controllers-Auth.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Shows\u0020login\u0020page\u0020and\u0020its\u0020form.",
            "url": "classes/App-Controllers-Auth.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_login\u0028\u0029",
            "name": "_login",
            "summary": "Validate\u0020login\u0020form,\u0020receive\u0020email\u0020through\u0020post\u0020form\u0020and\u0020verify\u0020password.",
            "url": "classes/App-Controllers-Auth.html#method__login"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_logout\u0028\u0029",
            "name": "_logout",
            "summary": "Validate\u0020correct\u0020logout\u0020request.",
            "url": "classes/App-Controllers-Auth.html#method__logout"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003AforgetPassword\u0028\u0029",
            "name": "forgetPassword",
            "summary": "Shows\u0020forget\u0020password\u0020page\u0020and\u0020its\u0020form.",
            "url": "classes/App-Controllers-Auth.html#method_forgetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_forgetPassword\u0028\u0029",
            "name": "_forgetPassword",
            "summary": "Validate\u0020forget\u0020password\u0020form,\u0020sending\u0020email\u0020through\u0020post\u0020form\u0020to\u0020verified\u0020email\u0020user.",
            "url": "classes/App-Controllers-Auth.html#method__forgetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "Shows\u0020reset\u0020password\u0020page\u0020and\u0020its\u0020form,\u0020this\u0020method\u0020only\u0020accessible\u0020if\u0020url\u0020provided\nis\u0020valid.",
            "url": "classes/App-Controllers-Auth.html#method_resetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_resetPassword\u0028\u0029",
            "name": "_resetPassword",
            "summary": "Validate\u0020reset\u0020password\u0020form,\u0020creating\u0020new\u0020password\u0020for\u0020particular\u0020user.",
            "url": "classes/App-Controllers-Auth.html#method__resetPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_verifyPassword\u0028\u0029",
            "name": "_verifyPassword",
            "summary": "Send\u0020password\u0020reset\u0020request\u0020to\u0020the\u0020user\u0020email\u0020provided\u0020in\u0020the\u0020form\nand\u0020encode\u0020userId\u0020\u0026\u0020userAttempt\u0020based\u0020on\u0020timestamp.",
            "url": "classes/App-Controllers-Auth.html#method__verifyPassword"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A_setSession\u0028\u0029",
            "name": "_setSession",
            "summary": "Attempt\u0020to\u0020set\u0020session\u0020data.",
            "url": "classes/App-Controllers-Auth.html#method__setSession"
        },                {
            "fqsen": "\\App\\Controllers\\Auth\u003A\u003A\u0024um",
            "name": "um",
            "summary": "UsersModel\u0020initiator.",
            "url": "classes/App-Controllers-Auth.html#property_um"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController",
            "name": "BaseController",
            "summary": "Class\u0020BaseController",
            "url": "classes/App-Controllers-BaseController.html"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003AinitController\u0028\u0029",
            "name": "initController",
            "summary": "Constructor,\u0020forced\u0020HTTPS\u0020and\u0020start\u0020the\u0020session.",
            "url": "classes/App-Controllers-BaseController.html#method_initController"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003A\u0024request",
            "name": "request",
            "summary": "Instance\u0020of\u0020the\u0020main\u0020Request\u0020object.",
            "url": "classes/App-Controllers-BaseController.html#property_request"
        },                {
            "fqsen": "\\App\\Controllers\\BaseController\u003A\u003A\u0024helpers",
            "name": "helpers",
            "summary": "An\u0020array\u0020of\u0020helpers\u0020to\u0020be\u0020loaded\u0020automatically\u0020upon\nclass\u0020instantiation.\u0020These\u0020helpers\u0020will\u0020be\u0020available\nto\u0020all\u0020other\u0020controllers\u0020that\u0020extend\u0020BaseController.",
            "url": "classes/App-Controllers-BaseController.html#property_helpers"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History",
            "name": "History",
            "summary": "This\u0020controller\u0020provides\u0020content\u0020management\u0020controller\u0020for\u0020displaying\u0020contents\u0020in\u0020host\/sejarah\u0020route.",
            "url": "classes/App-Controllers-Content-History.html"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Prepare\u0020HistoryModel.",
            "url": "classes/App-Controllers-Content-History.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Create\u0020form\u0020view\u0020of\u0020History\u0020Content.",
            "url": "classes/App-Controllers-Content-History.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History\u003A\u003A_updateHistory\u0028\u0029",
            "name": "_updateHistory",
            "summary": "Crud\u0020form\u0020validation\u0020for\u0020History\u0020Content.",
            "url": "classes/App-Controllers-Content-History.html#method__updateHistory"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\History\u003A\u003A\u0024hm",
            "name": "hm",
            "summary": "HistoryModel\u0020initiator.",
            "url": "classes/App-Controllers-Content-History.html#property_hm"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile",
            "name": "OrganizationProfile",
            "summary": "This\u0020controller\u0020provides\u0020content\u0020management\u0020controller\u0020for\u0020displaying\u0020contents\u0020in\u0020host\u0020route.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Prepare\u0020LandingModel,\u0020ActivitiesModel,\u0020MembersModel\u0020for\u0020every\nmethod\u0020available\u0020for\u0020simplicity.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Create\u0020view\u0020for\u0020index\u0020page\u0020navigation\u0020for\nchanging\u0020landing\u0020information.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003AmainInfo\u0028\u0029",
            "name": "mainInfo",
            "summary": "Create\u0020view\u0020form\u0020for\u0020mainInfo.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_mainInfo"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_updateMainInfo\u0028\u0029",
            "name": "_updateMainInfo",
            "summary": "Form\u0020validation\u0020and\u0020save\u0020data\u0020by\u0020model\u0020for\u0020mainInfo.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__updateMainInfo"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003AourActivities\u0028\u0029",
            "name": "ourActivities",
            "summary": "Create\u0020view\u0020form\u0020for\u0020ourActivities.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_ourActivities"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_updateOurActivities\u0028\u0029",
            "name": "_updateOurActivities",
            "summary": "Form\u0020validation\u0020for\u0020ourActivities.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__updateOurActivities"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003Amembers\u0028\u0029",
            "name": "members",
            "summary": "Prepare\u0020basic\u0020view\u0020for\u0020members\u0020table\u0020before\u0020retrieve\u0020its\u0020data\u0020from\u0020datatables.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_members"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_membersDatatable\u0028\u0029",
            "name": "_membersDatatable",
            "summary": "Members\u0020Datatables\u0020generator.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__membersDatatable"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_delete\u0028\u0029",
            "name": "_delete",
            "summary": "Members\u0020delete\u0020ajax\u0020call.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__delete"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003AmemberCrud\u0028\u0029",
            "name": "memberCrud",
            "summary": "Create\u0020form\u0020view\u0020for\u0020creating\u0020and\u0020updating\u0020member\u0020data.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method_memberCrud"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A_memberCrud\u0028\u0029",
            "name": "_memberCrud",
            "summary": "Form\u0020validation\u0020and\u0020save\u0020data\u0020handler\u0020for\u0020members.",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#method__memberCrud"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A\u0024lm",
            "name": "lm",
            "summary": "LandingModel\u0020initiator",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#property_lm"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A\u0024am",
            "name": "am",
            "summary": "ActivitiesModel\u0020initiator",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#property_am"
        },                {
            "fqsen": "\\App\\Controllers\\Content\\OrganizationProfile\u003A\u003A\u0024mm",
            "name": "mm",
            "summary": "MembersModel\u0020initiator",
            "url": "classes/App-Controllers-Content-OrganizationProfile.html#property_mm"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages",
            "name": "Messages",
            "summary": "This\u0020controller\u0020shows\u0020Messages\u0020data.",
            "url": "classes/App-Controllers-Data-Messages.html"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Prepare\u0020MessagesModel.",
            "url": "classes/App-Controllers-Data-Messages.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Prepare\u0020basic\u0020view\u0020for\u0020messages.",
            "url": "classes/App-Controllers-Data-Messages.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A_datatable\u0028\u0029",
            "name": "_datatable",
            "summary": "Messages\u0020Datatables\u0020generator.",
            "url": "classes/App-Controllers-Data-Messages.html#method__datatable"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A_updateStatus\u0028\u0029",
            "name": "_updateStatus",
            "summary": "Messages\u0020update\u0020read\/unread\u0020ajax\u0020call.",
            "url": "classes/App-Controllers-Data-Messages.html#method__updateStatus"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A_delete\u0028\u0029",
            "name": "_delete",
            "summary": "Delete\u0020messages\u0020ajax\u0020call.",
            "url": "classes/App-Controllers-Data-Messages.html#method__delete"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Messages\u003A\u003A\u0024msm",
            "name": "msm",
            "summary": "MessagesModel\u0020initiator.",
            "url": "classes/App-Controllers-Data-Messages.html#property_msm"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks",
            "name": "Pmpsks",
            "summary": "This\u0020controller\u0020shows\u0020PMKS\/PSKS\u0020data.",
            "url": "classes/App-Controllers-Data-Pmpsks.html"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Prepare\u0020basic\u0020view\u0020for\u0020PMKS\/PSKS\u0020table.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003A_datatable\u0028\u0029",
            "name": "_datatable",
            "summary": "PMKS\/PSKS\u0020Datatables\u0020generator.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method__datatable"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003A_updateStatus\u0028\u0029",
            "name": "_updateStatus",
            "summary": "PMKS\/PSKS\u0020update\u0020read\/unread\u0020ajax\u0020call.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method__updateStatus"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003A_delete\u0028\u0029",
            "name": "_delete",
            "summary": "Delete\u0020PMKS\/PSKS\u0020data\u0020ajax\u0020call.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method__delete"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003Acrud\u0028\u0029",
            "name": "crud",
            "summary": "Create\u0020form\u0020view\u0020for\u0020creating\nand\u0020updating\u0020PMKS\/PSKS\u0020data.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method_crud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003AspreadsheetCrud\u0028\u0029",
            "name": "spreadsheetCrud",
            "summary": "Create\u0020form\u0020view\u0020for\u0020creating\nPMKS\/PSKS\u0020data\u0020with\u0020Spreadsheet.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method_spreadsheetCrud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003A_crud\u0028\u0029",
            "name": "_crud",
            "summary": "Form\u0020validation\u0020and\u0020procedure\nto\u0020save\u0020data\u0020with\u0020PmpsksModel.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method__crud"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003AgetImages\u0028\u0029",
            "name": "getImages",
            "summary": "Get\u0020PMKS\/PSKS\u0020data\u0020images\u0020ajax\u0020call.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#method_getImages"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003A\u0024cm",
            "name": "cm",
            "summary": "CommunitiesModel\u0020initiator.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#property_cm"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003A\u0024pim",
            "name": "pim",
            "summary": "PmpsksImgModel\u0020initiator.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#property_pim"
        },                {
            "fqsen": "\\App\\Controllers\\Data\\Pmpsks\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "Constructor\u0020provided\u0020to\u0020prepare\u0020every\u0020model.",
            "url": "classes/App-Controllers-Data-Pmpsks.html#property_uri"
        },                {
            "fqsen": "\\App\\Controllers\\Home",
            "name": "Home",
            "summary": "Main\u0020Landing\u0020Page\u0020Controller.",
            "url": "classes/App-Controllers-Home.html"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Prepare\u0020LandingModel,\u0020ActivitiesModel,\u0020MembersModel,\u0020HistoryModel,\u0020and\u0020MessagesModel\u0020for\u0020every\nmethod\u0020available\u0020for\u0020simplicity.",
            "url": "classes/App-Controllers-Home.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Shows\u0020landing\u0020page\u0020information.",
            "url": "classes/App-Controllers-Home.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003Ahistory\u0028\u0029",
            "name": "history",
            "summary": "Shows\u0020history\u0020page\u0020information.",
            "url": "classes/App-Controllers-Home.html#method_history"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003AcontactUs\u0028\u0029",
            "name": "contactUs",
            "summary": "Shows\u0020contact\u0020us\u0020page\u0020and\u0020its\u0020form.",
            "url": "classes/App-Controllers-Home.html#method_contactUs"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003Asitemap\u0028\u0029",
            "name": "sitemap",
            "summary": "Shows\u0020sitemap\u0020information.",
            "url": "classes/App-Controllers-Home.html#method_sitemap"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A_sendMessage\u0028\u0029",
            "name": "_sendMessage",
            "summary": "Form\u0020validation\u0020and\u0020procedure\u0020to\u0020insert\u0020new\u0020messages\u0020to\u0020the\u0020database.",
            "url": "classes/App-Controllers-Home.html#method__sendMessage"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A_sendNotification\u0028\u0029",
            "name": "_sendNotification",
            "summary": "Sending\u0020notification\u0020procedure\u0020after\u0020person\u0020sent\u0020message\u0020to\u0020the\u0020application.",
            "url": "classes/App-Controllers-Home.html#method__sendNotification"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024lm",
            "name": "lm",
            "summary": "LandingModel\u0020initiator",
            "url": "classes/App-Controllers-Home.html#property_lm"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024am",
            "name": "am",
            "summary": "ActivitiesModel\u0020initiator",
            "url": "classes/App-Controllers-Home.html#property_am"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024mm",
            "name": "mm",
            "summary": "MembersModel\u0020initiator",
            "url": "classes/App-Controllers-Home.html#property_mm"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024hm",
            "name": "hm",
            "summary": "HistoryModel\u0020initiator.",
            "url": "classes/App-Controllers-Home.html#property_hm"
        },                {
            "fqsen": "\\App\\Controllers\\Home\u003A\u003A\u0024msm",
            "name": "msm",
            "summary": "MessagesModel\u0020initiator.",
            "url": "classes/App-Controllers-Home.html#property_msm"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Home",
            "name": "Home",
            "summary": "This\u0020controller\u0020used\u0020for\u0020dashboard\u0020and\u0020load\u0020private\u0020images\u0020\u0028logged\u0020in\u0020only\u0029.",
            "url": "classes/App-Controllers-User-Home.html"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Home\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Prepare\u0020dashboard\u0020view",
            "url": "classes/App-Controllers-User-Home.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Home\u003A\u003AloadImage\u0028\u0029",
            "name": "loadImage",
            "summary": "Provides\u0020function\u0020call\u0020for\u0020private\u0020images,\u0020called\u0020from\u0020host\/gambar\u002Dprivate\u003Fq\u003D...\u0020url",
            "url": "classes/App-Controllers-User-Home.html#method_loadImage"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile",
            "name": "Profile",
            "summary": "This\u0020controller\u0020purpose\u0020is\u0020to\u0020change\u0020user\u0020account\u0020details.",
            "url": "classes/App-Controllers-User-Profile.html"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020UsersModel.",
            "url": "classes/App-Controllers-User-Profile.html#method___construct"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "This\u0020method\u0020is\u0020to\u0020show\u0020form\u0020view\u0020of\u0020profile\/account\u0020settings.",
            "url": "classes/App-Controllers-User-Profile.html#method_index"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003A_updateProfile\u0028\u0029",
            "name": "_updateProfile",
            "summary": "Validate\u0020and\u0020submit\u0020form\u0020to\u0020database.",
            "url": "classes/App-Controllers-User-Profile.html#method__updateProfile"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003A_verifyEmail\u0028\u0029",
            "name": "_verifyEmail",
            "summary": "Send\u0020email\u0020method\u0020to\u0020new\u0020email\u0020posted\u0020on\u0020the\u0020form.",
            "url": "classes/App-Controllers-User-Profile.html#method__verifyEmail"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003AverifyEmail\u0028\u0029",
            "name": "verifyEmail",
            "summary": "Control\u0020email\u0020verification\u0020or\u0020when\u0020cancelling\u0020email\u0020verification,\nthis\u0020method\u0020only\u0020accessible\u0020if\u0020url\u0020provided\u0020is\u0020valid.",
            "url": "classes/App-Controllers-User-Profile.html#method_verifyEmail"
        },                {
            "fqsen": "\\App\\Controllers\\User\\Profile\u003A\u003A\u0024um",
            "name": "um",
            "summary": "UsersModel\u0020initiator.",
            "url": "classes/App-Controllers-User-Profile.html#property_um"
        },                {
            "fqsen": "\\App\\Filters\\SecurityFilter",
            "name": "SecurityFilter",
            "summary": "Security\u0020Filter\u0020are\u0020filter\u0020interface\u0020that\u0020runs\u0020before\u0020controller\u0020executed.",
            "url": "classes/App-Filters-SecurityFilter.html"
        },                {
            "fqsen": "\\App\\Filters\\SecurityFilter\u003A\u003Abefore\u0028\u0029",
            "name": "before",
            "summary": "",
            "url": "classes/App-Filters-SecurityFilter.html#method_before"
        },                {
            "fqsen": "\\App\\Filters\\SecurityFilter\u003A\u003Aafter\u0028\u0029",
            "name": "after",
            "summary": "",
            "url": "classes/App-Filters-SecurityFilter.html#method_after"
        },                {
            "fqsen": "\\checkAuth\u0028\u0029",
            "name": "checkAuth",
            "summary": "Main\u0020authentication\u0020function\u0020for\u0020Kartasolv\u0020application.",
            "url": "namespaces/default.html#function_checkAuth"
        },                {
            "fqsen": "\\filterOutput\u0028\u0029",
            "name": "filterOutput",
            "summary": "Filters\u0020data\u0020from\u0020Object,\u0020Array,\u0020or\u0020String\u0020to\u0020be\u0020escaped.",
            "url": "namespaces/default.html#function_filterOutput"
        },                {
            "fqsen": "\\htmlEscape\u0028\u0029",
            "name": "htmlEscape",
            "summary": "Returns\u0020HTML\u0020escaped\u0020variable.",
            "url": "namespaces/default.html#function_htmlEscape"
        },                {
            "fqsen": "\\encode\u0028\u0029",
            "name": "encode",
            "summary": "Encode\u0020data\u0020to\u0020random\u0020string.\u0020Useful\u0020for\u0020encode\u0020ID\u0020data.",
            "url": "namespaces/default.html#function_encode"
        },                {
            "fqsen": "\\decode\u0028\u0029",
            "name": "decode",
            "summary": "Decode\u0020data\u0020to\u0020random\u0020string.\u0020Useful\u0020for\u0020decode\u0020ID\u0020data.",
            "url": "namespaces/default.html#function_decode"
        },                {
            "fqsen": "\\show404\u0028\u0029",
            "name": "show404",
            "summary": "Showing\u0020404\u0020page.",
            "url": "namespaces/default.html#function_show404"
        },                {
            "fqsen": "\\getCaptchaSitekey\u0028\u0029",
            "name": "getCaptchaSitekey",
            "summary": "Retrieve\u0020Captcha\u0020Sitekey.",
            "url": "namespaces/default.html#function_getCaptchaSitekey"
        },                {
            "fqsen": "\\kartaPasswordHash\u0028\u0029",
            "name": "kartaPasswordHash",
            "summary": "Hash\u0020raw\u0020string\u0020to\u0020a\u0020password.",
            "url": "namespaces/default.html#function_kartaPasswordHash"
        },                {
            "fqsen": "\\kartaPasswordVerify\u0028\u0029",
            "name": "kartaPasswordVerify",
            "summary": "Verify\u0020string\u0020input\u0020to\u0020hashed\u0020password.",
            "url": "namespaces/default.html#function_kartaPasswordVerify"
        },                {
            "fqsen": "\\getMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "Simplification\u0020retrieving\u0020method\u0020from\u0020Services.",
            "url": "namespaces/default.html#function_getMethod"
        },                {
            "fqsen": "\\acceptFrom\u0028\u0029",
            "name": "acceptFrom",
            "summary": "Redirection\u0020function\u0020when\u0020submitted\u0020form\u0020source\/referrer\u0020is\u0020not\u0020from\u0020correct\u0020route.",
            "url": "namespaces/default.html#function_acceptFrom"
        },                {
            "fqsen": "\\removeProtocol\u0028\u0029",
            "name": "removeProtocol",
            "summary": "Removing\u0020protocol\u0020like\u0020http\u0020and\u0020https\u0020from\u0020url\u0020provided.",
            "url": "namespaces/default.html#function_removeProtocol"
        },                {
            "fqsen": "\\addProtocol\u0028\u0029",
            "name": "addProtocol",
            "summary": "Add\u0020protocol\u0020to\u0020provided\u0020url\u0020string.",
            "url": "namespaces/default.html#function_addProtocol"
        },                {
            "fqsen": "\\objectify\u0028\u0029",
            "name": "objectify",
            "summary": "Change\u0020associative\u0020array\/string\u0020into\u0020PHP\u0020Object.",
            "url": "namespaces/default.html#function_objectify"
        },                {
            "fqsen": "\\setFlash\u0028\u0029",
            "name": "setFlash",
            "summary": "Set\u0020session\u0020flashdata\u0020with\u0020custom\u0020format\u0020according\u0020Codeigniter\u00204\u0020session.",
            "url": "namespaces/default.html#function_setFlash"
        },                {
            "fqsen": "\\getFlash\u0028\u0029",
            "name": "getFlash",
            "summary": "Retrieve\u0020flash\u0020data.",
            "url": "namespaces/default.html#function_getFlash"
        },                {
            "fqsen": "\\parseMission\u0028\u0029",
            "name": "parseMission",
            "summary": "Parse\u0020mission\u0020string\u0020from\u0020the\u0020database\u0020into\u0020generated\u0020string\u0020for\u0020textarea\u0020input.",
            "url": "namespaces/default.html#function_parseMission"
        },                {
            "fqsen": "\\setInvalid\u0028\u0029",
            "name": "setInvalid",
            "summary": "Sets\u0020an\u0020input\u0020to\u0020be\u0020invalid\u0020by\u0020returning\u0020is\u002Dinvalid\u0020class\u0020to\u0020the\u0020input.",
            "url": "namespaces/default.html#function_setInvalid"
        },                {
            "fqsen": "\\showInvalidFeedback\u0028\u0029",
            "name": "showInvalidFeedback",
            "summary": "Retrieves\u0020error\u0020message\u0020from\u0020form\u0020validation\u0020input.",
            "url": "namespaces/default.html#function_showInvalidFeedback"
        },                {
            "fqsen": "\\countTable\u0028\u0029",
            "name": "countTable",
            "summary": "Data\u0020counter\u0020for\u0020certain\u0020table,\u0020currently\u0020the\u0020param\u0020only\u0020used\u0020for\u0020Communities\u0020table\u0020joined\u0020to\u0020PMPSKS\u0020Table.",
            "url": "namespaces/default.html#function_countTable"
        },                {
            "fqsen": "\\parseTest\u0028\u0029",
            "name": "parseTest",
            "summary": "Parsing\u0020test\u0020cases\u0020array.\u0020Use\u0020only\u0020for\u0020unit\u0020testing.",
            "url": "namespaces/default.html#function_parseTest"
        },                {
            "fqsen": "\\isSamePage\u0028\u0029",
            "name": "isSamePage",
            "summary": "Check\u0020wether\u0020same\u0020page\u0020or\u0020not\u0020for\u0020navigation\u0020bar.",
            "url": "namespaces/default.html#function_isSamePage"
        },                {
            "fqsen": "\\getSidebarMenu\u0028\u0029",
            "name": "getSidebarMenu",
            "summary": "Retrieve\u0020sidebar\u0020menus\u0020based\u0020on\u0020roles.",
            "url": "namespaces/default.html#function_getSidebarMenu"
        },                {
            "fqsen": "\\isSameController\u0028\u0029",
            "name": "isSameController",
            "summary": "Check\u0020wether\u0020same\u0020controller\u0020or\u0020not\u0020for\u0020navigation\u0020bar.",
            "url": "namespaces/default.html#function_isSameController"
        },                {
            "fqsen": "\\getCallToAction\u0028\u0029",
            "name": "getCallToAction",
            "summary": "Retrieve\u0020Call\u0020to\u0020Action\u0020url\u0020and\u0020text\u0020from\u0020database.",
            "url": "namespaces/default.html#function_getCallToAction"
        },                {
            "fqsen": "\\getUserName\u0028\u0029",
            "name": "getUserName",
            "summary": "Retrieve\u0020Logged\u0020In\u0020User\u0020Name\u0020from\u0020database.",
            "url": "namespaces/default.html#function_getUserName"
        },                {
            "fqsen": "\\getMissions\u0028\u0029",
            "name": "getMissions",
            "summary": "Function\u0020for\u0020displaying\u0020missions\u0020on\u0020the\u0020landing\u0020page.",
            "url": "namespaces/default.html#function_getMissions"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager",
            "name": "DatabaseManager",
            "summary": "DatabaseManager\u0020is\u0020a\u0020library\u0020made\u0020to\u0020simplify\u0020query\u0020builder\u0020especially\u0020to\u0020retrieve\u0020data\u0020and\u0020displays\u0020it\u0020to\nDatatables\u0020with\u0020server\u0020side\u0020processing.",
            "url": "classes/App-Libraries-DatabaseManager.html"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020connection\u0020to\u0020the\u0020database.",
            "url": "classes/App-Libraries-DatabaseManager.html#method___construct"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003AfilterDatatables\u0028\u0029",
            "name": "filterDatatables",
            "summary": "Generate\u0020datatables\u0020query\u0020based\u0020on\u0020user\u0020input.",
            "url": "classes/App-Libraries-DatabaseManager.html#method_filterDatatables"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003AcountAll\u0028\u0029",
            "name": "countAll",
            "summary": "Count\u0020queried\u0020result.",
            "url": "classes/App-Libraries-DatabaseManager.html#method_countAll"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020database\u0020function\u0020with\u0020QueryBuilder.",
            "url": "classes/App-Libraries-DatabaseManager.html#method_read"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003AmakeGroup\u0028\u0029",
            "name": "makeGroup",
            "summary": "Group\u0020Queries.",
            "url": "classes/App-Libraries-DatabaseManager.html#method_makeGroup"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003A\u0024db",
            "name": "db",
            "summary": "Prepare\u0020the\u0020db\u0020connection.",
            "url": "classes/App-Libraries-DatabaseManager.html#property_db"
        },                {
            "fqsen": "\\App\\Libraries\\DatabaseManager\u003A\u003A\u0024builder",
            "name": "builder",
            "summary": "Prepare\u0020builder\u0020variable.",
            "url": "classes/App-Libraries-DatabaseManager.html#property_builder"
        },                {
            "fqsen": "\\App\\Libraries\\ImageUploader",
            "name": "ImageUploader",
            "summary": "ImageUploader\u0020that\u0020use\u0020Codeigniter\u00204\u0027s\u0020File\u0020Uploader\u0020Class",
            "url": "classes/App-Libraries-ImageUploader.html"
        },                {
            "fqsen": "\\App\\Libraries\\ImageUploader\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Upload\u0020method.",
            "url": "classes/App-Libraries-ImageUploader.html#method_upload"
        },                {
            "fqsen": "\\App\\Libraries\\ImageUploader\u003A\u003A_convertToWebp\u0028\u0029",
            "name": "_convertToWebp",
            "summary": "Convert\u0020file\u0020in\u0020addressed\u0020filepath\u0020into\u0020webp.",
            "url": "classes/App-Libraries-ImageUploader.html#method__convertToWebp"
        },                {
            "fqsen": "\\App\\Libraries\\Model",
            "name": "Model",
            "summary": "Extends\u0020from\u0020original\u0020Codeigniter\u0020Model.",
            "url": "classes/App-Libraries-Model.html"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003AgetValidationRules\u0028\u0029",
            "name": "getValidationRules",
            "summary": "Returns\u0020the\u0020model\u0027s\u0020defined\u0020validation\u0020rules\u0020so\u0020that\u0020they\ncan\u0020be\u0020used\u0020elsewhere,\u0020if\u0020needed.",
            "url": "classes/App-Libraries-Model.html#method_getValidationRules"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Fetches\u0020the\u0020row\u0020of\u0020database",
            "url": "classes/App-Libraries-Model.html#method_find"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003AsetModifiedBy\u0028\u0029",
            "name": "setModifiedBy",
            "summary": "Assign\u0020modified_by\u0020field\u0020in\u0020the\u0020database.",
            "url": "classes/App-Libraries-Model.html#method_setModifiedBy"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003AsetCreatedBy\u0028\u0029",
            "name": "setCreatedBy",
            "summary": "Assign\u0020created_by\u0020field\u0020in\u0020the\u0020database.",
            "url": "classes/App-Libraries-Model.html#method_setCreatedBy"
        },                {
            "fqsen": "\\App\\Libraries\\Model\u003A\u003AsetDeletedBy\u0028\u0029",
            "name": "setDeletedBy",
            "summary": "Assign\u0020deleted_by\u0020field\u0020in\u0020the\u0020database.",
            "url": "classes/App-Libraries-Model.html#method_setDeletedBy"
        },                {
            "fqsen": "\\App\\Libraries\\RedirectResponse",
            "name": "RedirectResponse",
            "summary": "Override\u0020RedirectResponse\u0020class.",
            "url": "classes/App-Libraries-RedirectResponse.html"
        },                {
            "fqsen": "\\App\\Libraries\\RedirectResponse\u003A\u003Ato\u0028\u0029",
            "name": "to",
            "summary": "Sets\u0020the\u0020URI\u0020to\u0020redirect\u0020to\u0020and,\u0020optionally,\u0020the\u0020HTTP\u0020status\u0020code\u0020to\u0020use.",
            "url": "classes/App-Libraries-RedirectResponse.html#method_to"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel",
            "name": "ActivitiesModel",
            "summary": "Table\u0020Info_activities\u0020model.",
            "url": "classes/App-Models-ActivitiesModel.html"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\ActivitiesModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-ActivitiesModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel",
            "name": "CommunitiesModel",
            "summary": "Table\u0020Communities\u0020model.",
            "url": "classes/App-Models-CommunitiesModel.html"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003AgetPMKSDatatable\u0028\u0029",
            "name": "getPMKSDatatable",
            "summary": "Retrieve\u0020Datatables.",
            "url": "classes/App-Models-CommunitiesModel.html#method_getPMKSDatatable"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003AgetPSKSDatatable\u0028\u0029",
            "name": "getPSKSDatatable",
            "summary": "Retrieve\u0020Datatables.",
            "url": "classes/App-Models-CommunitiesModel.html#method_getPSKSDatatable"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024useSoftDeletes",
            "name": "useSoftDeletes",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_useSoftDeletes"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024beforeInsert",
            "name": "beforeInsert",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_beforeInsert"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024afterDelete",
            "name": "afterDelete",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_afterDelete"
        },                {
            "fqsen": "\\App\\Models\\CommunitiesModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-CommunitiesModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel",
            "name": "HistoryModel",
            "summary": "Table\u0020Info_history\u0020model.",
            "url": "classes/App-Models-HistoryModel.html"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\HistoryModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-HistoryModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\LandingModel",
            "name": "LandingModel",
            "summary": "Table\u0020Info_landing\u0020model.",
            "url": "classes/App-Models-LandingModel.html"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003AgetCallToAction\u0028\u0029",
            "name": "getCallToAction",
            "summary": "Retrieve\u0020Call\u0020to\u0020Action\u0020data.",
            "url": "classes/App-Models-LandingModel.html#method_getCallToAction"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\LandingModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-LandingModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\MembersModel",
            "name": "MembersModel",
            "summary": "Table\u0020Members\u0020model.",
            "url": "classes/App-Models-MembersModel.html"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003AgetMembers\u0028\u0029",
            "name": "getMembers",
            "summary": "Get\u0020members\u0020data\u0020for\u0020landing\u0020page.",
            "url": "classes/App-Models-MembersModel.html#method_getMembers"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003AgetDatatable\u0028\u0029",
            "name": "getDatatable",
            "summary": "Retrieve\u0020Datatables.",
            "url": "classes/App-Models-MembersModel.html#method_getDatatable"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024useSoftDeletes",
            "name": "useSoftDeletes",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_useSoftDeletes"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024beforeInsert",
            "name": "beforeInsert",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_beforeInsert"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024afterDelete",
            "name": "afterDelete",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_afterDelete"
        },                {
            "fqsen": "\\App\\Models\\MembersModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-MembersModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel",
            "name": "MessagesModel",
            "summary": "Table\u0020Messages\u0020model.",
            "url": "classes/App-Models-MessagesModel.html"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003AgetDatatable\u0028\u0029",
            "name": "getDatatable",
            "summary": "Retrieve\u0020Datatables.",
            "url": "classes/App-Models-MessagesModel.html#method_getDatatable"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024useSoftDeletes",
            "name": "useSoftDeletes",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_useSoftDeletes"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024beforeUpdate",
            "name": "beforeUpdate",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_beforeUpdate"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024afterDelete",
            "name": "afterDelete",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_afterDelete"
        },                {
            "fqsen": "\\App\\Models\\MessagesModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-MessagesModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel",
            "name": "PmpsksImgModel",
            "summary": "Table\u0020Pmpsks_img\u0020model.",
            "url": "classes/App-Models-PmpsksImgModel.html"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003AgetImages\u0028\u0029",
            "name": "getImages",
            "summary": "Retrieve\u0020PMPSKS\u0020image\u0020based\u0020on\u0020Community\u0020Id.",
            "url": "classes/App-Models-PmpsksImgModel.html#method_getImages"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003AdeleteImages\u0028\u0029",
            "name": "deleteImages",
            "summary": "Delete\u0020image\u0020method\u0020and\u0020unlink\/delete\u0020from\u0020directory\u0020function.",
            "url": "classes/App-Models-PmpsksImgModel.html#method_deleteImages"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\PmpsksImgModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-PmpsksImgModel.html#property_validationRules"
        },                {
            "fqsen": "\\App\\Models\\UsersModel",
            "name": "UsersModel",
            "summary": "Table\u0020Users\u0020model.",
            "url": "classes/App-Models-UsersModel.html"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003AgetFromEmail\u0028\u0029",
            "name": "getFromEmail",
            "summary": "Retrieve\u0020user\u0020data\u0020based\u0020on\u0020email.",
            "url": "classes/App-Models-UsersModel.html#method_getFromEmail"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024useTimestamps",
            "name": "useTimestamps",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_useTimestamps"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024allowedFields",
            "name": "allowedFields",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_allowedFields"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024returnType",
            "name": "returnType",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_returnType"
        },                {
            "fqsen": "\\App\\Models\\UsersModel\u003A\u003A\u0024validationRules",
            "name": "validationRules",
            "summary": "",
            "url": "classes/App-Models-UsersModel.html#property_validationRules"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Config",
            "name": "Config",
            "summary": "",
            "url": "namespaces/config.html"
        },                {
            "fqsen": "\\App\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-controllers.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Controllers\\Content",
            "name": "Content",
            "summary": "",
            "url": "namespaces/app-controllers-content.html"
        },                {
            "fqsen": "\\App\\Controllers\\Data",
            "name": "Data",
            "summary": "",
            "url": "namespaces/app-controllers-data.html"
        },                {
            "fqsen": "\\App\\Controllers\\User",
            "name": "User",
            "summary": "",
            "url": "namespaces/app-controllers-user.html"
        },                {
            "fqsen": "\\App\\Filters",
            "name": "Filters",
            "summary": "",
            "url": "namespaces/app-filters.html"
        },                {
            "fqsen": "\\App\\Libraries",
            "name": "Libraries",
            "summary": "",
            "url": "namespaces/app-libraries.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        }            ]
);
